- type: replace
  path: /instance_groups/-
  value:
    name: apply-specs
    azs: [z1,z2,z3]
    lifecycle: errand
    instances: 1
    jobs:
    - name: apply-specs
      release: kubo
      properties:
        addons-spec: ((addons-spec))

